//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buchung()
        {
            this.Treffpunkts = new HashSet<Treffpunkt>();
        }
    
        public int B_Buchung_Id { get; set; }
        public Nullable<System.DateTime> B_Datum { get; set; }
        public Nullable<int> B_Personenanzahl { get; set; }
        public string B_Preis { get; set; }
        public Nullable<int> B_K_Kunde_Id { get; set; }
        public Nullable<short> B_To_Tour_Id { get; set; }
        public Nullable<short> B_F_Fremdenfuehrer_Id { get; set; }
        public Nullable<short> B_S_Sprach_Id { get; set; }
        public Nullable<int> B_T_Treffpunkt_Id { get; set; }
    
        public virtual Fremdenfuehrer Fremdenfuehrer { get; set; }
        public virtual Kunde Kunde { get; set; }
        public virtual Sprache Sprache { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Treffpunkt Treffpunkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treffpunkt> Treffpunkts { get; set; }
    }
}
