//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fremdenfuehrer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fremdenfuehrer()
        {
            this.Buchungs = new HashSet<Buchung>();
        }
    
        public short F_Fremdenfuehrer_Id { get; set; }
        public string F_Vorname { get; set; }
        public string F_Nachname { get; set; }
        public Nullable<short> F_S_Sprach_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
        public virtual Sprache Sprache { get; set; }
    }
}
