//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Buchungs = new HashSet<Buchung>();
        }
    
        public int K_Kunde_Id { get; set; }
        public string K_Vorname { get; set; }
        public string K_Nachname { get; set; }
        public Nullable<System.DateTime> K_GebDatum { get; set; }
        public string K_Strasse { get; set; }
        public string K_Hausnr { get; set; }
        public string K_Ort { get; set; }
        public string K_Land { get; set; }
        public string K_PLZ { get; set; }
        public string K_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
    }
}
