//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tour_DBEntities : DbContext
    {
        public Tour_DBEntities()
            : base("name=Tour_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buchung> Buchungs { get; set; }
        public virtual DbSet<Fremdenfuehrer> Fremdenfuehrers { get; set; }
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Sprache> Spraches { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<Treffpunkt> Treffpunkts { get; set; }
    }
}
