//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprache
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprache()
        {
            this.Buchungs = new HashSet<Buchung>();
            this.Fremdenfuehrers = new HashSet<Fremdenfuehrer>();
        }
    
        public short S_Sprach_Id { get; set; }
        public string S_Language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fremdenfuehrer> Fremdenfuehrers { get; set; }
    }
}
