//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2TourMVVM_6AKIF_JaenV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treffpunkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treffpunkt()
        {
            this.Buchungs = new HashSet<Buchung>();
        }
    
        public int T_Treffpunkt_Id { get; set; }
        public string T_Strasse { get; set; }
        public string T_Hausnr { get; set; }
        public string T_Ort { get; set; }
        public string T_PLZ { get; set; }
        public Nullable<int> T_B_Buchung_Id { get; set; }
        public Nullable<short> T_To_Tour_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchungs { get; set; }
        public virtual Buchung Buchung { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
